# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Compile
version:      0.18
version_from: 
installdirs:  site
requires:
    Data::Dump::Streamer:          2.03
    IO:                            1.22
    Math::BigInt:                  1.77
    Test::Deep:                    0.095
    Test::More:                    0.54
    XML::LibXML:                   1.63

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
