--- #YAML:1.0
name:                XML-Compile
version:             0.97
abstract:            Compilation based XML processing
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    bignum:                        0.1
    Digest::MD5:                   2.36
    IO:                            1.22
    Log::Report:                   0.17
    Math::BigInt:                  1.77
    Math::BigRat:                  0.1
    Test::Deep:                    0.095
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile::Tester:          0.03
    XML::LibXML:                   1.65
    XML::RegExp:                   0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
