--- #YAML:1.0
name:                XML-Compile
version:             0.68
abstract:            Compilation based XML processing
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO:                            1.22
    Log::Report:                   0.09
    Math::BigInt:                  1.77
    Test::Deep:                    0.095
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::LibXML:                   1.65
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
