
=head1 NAME

XML::Compile::Schema::NameSpaces - Connect name-spaces from schemas



=head1 SYNOPSIS

 # Used internally by XML::Compile::Schema
 my $nss = XML::Compile::Schema::NameSpaces->new;
 $nss->add($schema);


=head1 DESCRIPTION

This module keeps overview on a set of schema's.



=head1 METHODS


=head2 Constructors


$obj-E<gt>B<new>(OPTIONS)

=over 4

=back

=head2 Accessors


$obj-E<gt>B<add>(SCHEMA)

=over 4

Adds the L<XML::Compile::Schema::Instance|XML::Compile::Schema::Instance> object to the internal
knowledge of this object.

=back

$obj-E<gt>B<findElement>(ADDRESS|(URI,NAME))

=over 4

Lookup the definition for the specified element, which is constructed as
C< {uri}name > or as seperate URI and NAME.

=back

$obj-E<gt>B<findID>(ADDRESS|(URI,ID))

=over 4

Lookup the definition for the specified id, which is constructed as
C< uri#id > or as seperate URI and ID.

=back

$obj-E<gt>B<findType>(ADDRESS|(URI,NAME))

=over 4

Lookup the definition for the specified type, which is constructed as
C< {uri}name > or as seperate URI and NAME.

=back

$obj-E<gt>B<namespace>(URI)

=over 4

Returns a list of L<XML::Compile::Schema::Instance|XML::Compile::Schema::Instance> objects which have
the URI as target namespace.

=back

$obj-E<gt>B<namespaces>

=over 4

Returns the list of names defined until now.

=back

$obj-E<gt>B<schemas>(URI)

=over 4

We need the name-space; when it is lacking then import must help.

=back









=head1 REFERENCES

See the XML::Compile website at L<http://perl.overmeer.net/xml-compile/> for more details.

=head1 COPYRIGHTS

Module version 0.05.
Written by Mark Overmeer (mark@overmeer.net).  See the ChangeLog for
other contributors.

Copyright (c) 2006 by the author(s). All rights reserved.  This program
is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.


