
=head1 NAME

XML::Compile::Schema::XmlTemplate - bricks to create an XML example



=head1 SYNOPSIS

 my $schema = XML::Compile::Schema->new(...);
 print $schema->template(XML => $type, ...);


=head1 DESCRIPTION

The translator understands schema's, but does not encode that into
actions. Given a type, this will produce an example XML output.











=head1 REFERENCES

See the XML::Compile website at L<http://perl.overmeer.net/xml-compile/> for more details.

=head1 COPYRIGHTS

Module version 0.10.
Written by Mark Overmeer (mark@overmeer.net).  See the ChangeLog for
other contributors.

Copyright (c) 2006 by the author(s). All rights reserved.  This program
is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.


